apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "python-flask-sample-app.fullname" . }}
  labels:
    app: {{ template "python-flask-sample-app.name" . }}
    chart: {{ template "python-flask-sample-app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "python-flask-sample-app.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "python-flask-sample-app.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ template "image.tag" . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          resources:
{{ toYaml .Values.resources | indent 12 }}
